version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: three_tier_frontend
    ports:
      - "8080:80"           # open http://localhost:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: three_tier_backend
    ports:
      - "3001:3000"         # API at http://localhost:3001
    environment:
      - PORT=3000
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: three_tier_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: